---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: nats-release-ci
- name: release-repo
- name: release-repo-master

outputs:
- name: final-release-repo

run:
  path: nats-release-ci/ci/tasks/create-final-nats-release/task

params:
  GIT_COMMIT_USERNAME: CI Bot
  GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  RUNTIME_CI_DIR: nats-release-ci
  RELEASE_NAME:
  MASTER_BRANCH:
  RELEASE_REPO_DIR: release-repo
  FINAL_RELEASE_REPO_DIR: final-release-repo
  GCP_NATS_BLOBSTORE_SERVICE_ACCOUNT_KEY:
