---
image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

platform: linux

inputs:
  - name: nats-release-ci
  - name: master-release

outputs:
  - name: release-notes

run:
  path: nats-release-ci/ci/tasks/build-release-notes/task

params:
  SOURCE_DIR: master-release
  OUTPUT_DIR: release-notes
  TRACKER_API_TOKEN:
