---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: bbl-state
- name: nats-release-ci
- name: bosh-bootloader

outputs:
- name: updated-bbl-state

params:
  ENVIRONMENT: ~
  IS_BOSH_LITE: false
  GIT_COMMIT_EMAIL:
  GIT_COMMIT_USERNAME:

run:
  path: nats-release-ci/ci/tasks/add-parent-dns/task
