name: GitHub Actions
on:
  pull_request:
    branches:
      - develop
jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    container: cloudfoundry/tas-runtime-build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: unit-and-integration-tests
        run: |
          ginkgo \
          --keep-going \
          --trace \
          -r \
          --fail-on-pending \
          --randomize-all \
          --race \
          --timeout 20m \
          --flake-attempts 2 \
          -p
